aspnet/IISIntegration

test/TestSites/wwwroot/web.config

@davidfowl @muratg @victorhurdugaci 
Victor, this is one of the last blockers for the x-plat tests.

Enable windows auth in tests via web.config.

---

src/Microsoft.AspNet.IISPlatformHandler/AuthenticationHandler.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerDefaults.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddlewareExtensions.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
src/Microsoft.AspNet.IISPlatformHandler/Microsoft.AspNet.IISPlatformHandler.xproj
src/Microsoft.AspNet.IISPlatformHandler/project.json
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/NtlmAuthentation.config
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/NtlmAuthentationTest.cs

#1 @HaoK @davidfowl @muratg 
This integrates IISPlatformHandlerMiddleware with the authentication infrastructure to:
1. Authenticate the user and set HttpContext.User, as well as respond to Authenticate calls.
2. Accept Challenges and set 401s. We don't set the headers because IIS will.
Note there's no way for us to detect what auth is actually enabled in IIS so we assume it's Negotiate and NTLM by default.

Implement a full authentication handler.

---

test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/HelloWorldTest.cs
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/HttpsTest.cs
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/NtlmAuthentationTest.cs

Under some failure conditions test requests can take 100s to timeout, and then they are retried 60 times for a total of 1.3 hours per test failure. This can cause the entire test pass to time out. Lowering this to a maximum of 5s per request, and 30 retires, for a maximum of 2.5 minutes per test failure.
@muratg

Lower integration test timeouts.

---

test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/HelloWorldTest.cs
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/HttpsTest.cs
test/Microsoft.AspNet.IISPlatformHandler.FunctionalTests/NtlmAuthentationTest.cs

@cesarbs @rynowak @davidfowl @Eilon 
This addresses some test failures introduced by the signing changes. The tests default to publishing as source and because they had a project dependency on IISPlatformHandler it was also being published as source. When the test app tried to compile IISPlatformHandler at runtime it failed because it couldn't find the key.snk singing file since it wasn't published with the sources. 
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocat
ion. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.IISPlatformHandler, Version=
1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. General Exception (Exception from HRESULT:
0x80131500) ---> …
```

[RC1 Tests] Publish tests with no-source to avoid signing issue.

---

samples/IISSample/Startup.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerAddressExtensions.cs
src/Microsoft.AspNet.IISPlatformHandler/project.json
test/TestSites/Program.cs

#14, 52 
Replaces https://github.com/aspnet/IISIntegration/pull/60
Depends on https://github.com/aspnet/Hosting/pull/566
@davidfowl @JunTaoLuo

Add IWebApplicationBuilder.UseIISPlatformHandlerUrl, include path base

---

samples/IISSample/Startup.cs
src/Microsoft.AspNet.IISPlatformHandler/ForwardedTlsConnectionFeature.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
src/Microsoft.AspNet.IISPlatformHandler/project.json

Forward client certificates.

---

src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
test/Microsoft.AspNet.IISPlatformHandler.Tests/HttpPlatformHandlerMiddlewareTests.cs

This is changing with the next version of HttpPlatformHandler so all the custome headers use the same naming scheme.
Do not merge yet or the tests will fail.
@davidfowl @pakrym

Rename windows auth forwarder header to MS-PLATFORM-HANDLER-WINAUTHTOKEN.

---

src/dotnet-publish-iis/Program.cs
src/dotnet-publish-iis/PublishIISCommand.cs
src/dotnet-publish-iis/WebConfigTransform.cs
src/dotnet-publish-iis/project.json
test/dotnet-publish-iis.Tests/PublishIISCommandFacts.cs
test/dotnet-publish-iis.Tests/WebConfigTransformFacts.cs
test/dotnet-publish-iis.Tests/dotnet-publish-iis.Tests.xproj
test/dotnet-publish-iis.Tests/project.json

- moving command logic to a dedicated class
- adding logic for reading webroot value from a parameter, hosting.json file and folder structure
- reading application name from project.json instead of a parameter

dotnet-publish-iis refactoring

---

src/dotnet-publish-iis/PublishIISCommand.cs

One scenario it is useful is where the webroot does not contain any files. In this case even if the webroot is included in the "content" section dotnet publish does will not publish it.

Creating webroot if one does not exists

---

samples/IISSample/Startup.cs
src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs
src/Microsoft.AspNetCore.Server.IISIntegration/IISWebHostExtensions.cs
src/Microsoft.AspNetCore.Server.IISIntegration/project.json
test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs
test/TestSites/StartupHttpsHelloWorld.cs

#95 @DamianEdwards @davidfowl @muratg @pranavkm 
FYI: I'll need to re-order the repo dependencies for this.
It's currently:
`Hosting -> Kestrel -> IISIntegration -> ServerTests -> BasicMiddleware`
I'll need to change it to:
`Hosting -> Kestrel -> BasicMiddleware -> IISIntegration -> ServerTests`
And remove the IIS references from the BasicMiddleware samples.

Add the ForwardedHeadersMiddleware by default.

---

src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Program.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/PublishIISCommand.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/PublishIISCommandFacts.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs

Enabling publishing portable apps

---

src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs

Removing %LAUNCHER_ARGS% from arguments for portable apps

---

src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs

#141 @blowdart 
@Eilon @DamianEdwards Please approve for RC2.

Require the MSAspNetCoreToken or send a 400.

---

test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/project.json
test/TestSites/project.json

Cleaning up project.json so restore works without --infer-runtimes

---

src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs

#140 @davidfowl @Eilon @muratg @DamianEdwards 
This fixes HTTPS and RemoteIpAddress issues on azure.

Disable header symmetry check on azure

---

test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs

issue: #187 
buddy build note: these two tests fail on Windows 2008 platform only for the moment. disable during the investigation.

disable two failed tests temporarily

---

src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs

#102 @shirhatti @pan-wang @davidfowl @muratg @NTaylorMullen 
Filter out DEBUG requests only when the debugger is attached. This is a mitigation for v1.0.
Post-v1.0 we plan to implement [auto-startup](https://github.com/aspnet/IISIntegration/issues/161) which will remove the need for the DEBUG request in the next tooling release.

Filter out DEBUG requests under the debugger.

---

src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs

#242 @davidfowl @JunTaoLuo @shirhatti @muratg 
Users too often break IIS by doing the following:
```
new WebHostBuilder()
.UseKestrel()
.UseIISIntegration()
.UseUrls("http://mysite.com:80/");
```
This change delays registering IIS's dynamic url until Build is called so it won't be overwritten by UseUrls.

Delay registering the url until Build

---

src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs
src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs

Switch to UsePathBase instead of relying on Kestrel feature #236

---

.gitignore
IISIntegration.sln
NuGetPackageVerifier.json
makefile.shade
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Internal/AnsiColorExtensions.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Internal/AnsiConsole.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Internal/Reporter.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Microsoft.AspNetCore.Server.IISIntegration.Tools.nuspec
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Microsoft.AspNetCore.Server.IISIntegration.Tools.xproj
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Program.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Properties/AssemblyInfo.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/PublishIISCommand.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
src/Microsoft.AspNetCore.Server.IISIntegration.Tools/project.json
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests.xproj
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/PublishIISCommandFacts.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/project.json
tools/NuGetPackager/PackCommand.cs
tools/NuGetPackager/Program.cs
tools/NuGetPackager/project.json

Resolves #289 
NB: this tool will be deprecated, but we need a version that works on 1.1 runtime until .NET Core SDK for MSBuild becomes available.
cc @muratg @Eilon

Produce dotnet-publish-iis for 1.1 runtime

---

test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs
test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs
test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/NtlmAuthentationTest.cs

- follow-up to 8ae481c
- sites are also built for .NET 4.5.2 in desktop runs

Use .NET 4.5.2 target framework when deploying test sites

---

samples/IISSample/Properties/launchSettings.json
samples/IISSample/Startup.cs
src/Microsoft.AspNetCore.Server.IISIntegration/IISHostingStartup.cs

@DamianEdwards @shirhatti @glennc 
Note ASPNETCORE_HOSTINGSTARTUPASSEMBLIES is defined in the launch settings until ANCM defines it.

Implement IISHostingStartup

---

test/IISIntegration.FunctionalTests/HelloWorldTest.cs
test/IISIntegration.FunctionalTests/HttpsTest.cs
test/IISIntegration.FunctionalTests/NtlmAuthentationTest.cs

The `LoggedTest` helper has been moved to `Microsoft.Extensions.Logging.Testing` repo.
React to aspnet/Hosting#1039

remove integration test logging

---

src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
test/IISIntegration.FunctionalTests/HelloWorldTest.cs
test/TestSites/StartupHelloWorld.cs

IIS already limits the request body size so this avoids having to configure it both in IIS and Kestrel.

Clear MaxRequestBodySize

---

src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
test/TestSites/StartupHelloWorld.cs

The Win7 tests caught this because those were the only agents using the latest ANCM version. Everything else passed using the backcompat code path.

Fix auth enabled check

---

samples/IISSample/Startup.cs
src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
src/Microsoft.AspNetCore.Server.IISIntegration/IISOptions.cs

#391 @PinpointTownes @DamianEdwards

Add back the DisplayName setting

---

src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs

- Today we use localhost which binds to both the ipv4 and ipv6 addresses.
ANCM never communicates over ipv6 so it's pointless. This should also properly crash
the process if the ipv4 address fails to bind (which we've seen reports in real applications for).

Use ipv4 when binding to ANCM port

---

build/dependencies.props
korebuild-lock.txt
src/AspNetCore/Src/applicationinfo.cpp

Load the hostfxr parameters if the application isn't loaded, rather than when the request handler is loaded. This is because we store the hostfxr parameters in the aspnetcore_config, which will be deleted on recycle. 
For #522. I updated dependencies too because out of process had pipeline errors in kestrel.

Always load hostfxr parameters if the app isn't loaded

---

src/RequestHandler/inprocess/inprocessapplication.cpp

There was an AV from the coreclr because we freed stdout/err before the app was closed. Though the coreclr should detect this, we can swap the order to hopefully avoid the AV.

Free stdout after app closes

---

src/RequestHandler/inprocess/inprocessapplication.h

For #521 
I believe this issue only occurred in Debug builds. Adding the WINAPI is the same as adding __stdcall, which I believe is needed as these functions are defined in managed.

Fixes bitness alignment issue for 32 bit builds

---

src/AspNetCore/Src/applicationinfo.cpp
src/CommonLib/hostfxr_utility.cpp

Two issues:
- Didn't do pointer arithmetic when iterating through paths
- Didn't add 2 when calling index of on a string of 2 characters.
This again means only the first dotnet on your path will be used (for preview1). @shirhatti should we just tell customers to use 64 bit app pools?

Fix path searching for where.exe and request handler parsing

---

test/WebSites/InProcessWebSite/Startup.cs

Apparently it is a bad idea to allocate 200MB in mem at the same time <_<. Fixes some AppVeyor failures.

Chunk writes to file

---

src/CommonLib/CommonLib.vcxproj
src/CommonLib/SRWLockWrapper.cpp
src/CommonLib/SRWLockWrapper.h
src/CommonLib/application.cpp
src/CommonLib/application.h
src/CommonLib/stdafx.h
src/RequestHandler/inprocess/inprocessapplication.cpp
src/RequestHandler/inprocess/inprocessapplication.h

This is exploratory PR which tries to explore improving our error handling/resource management patterns in native code. Main goal is to lower entry level and modernize the codebase.
Basic ideas:
1. Use RAII when possible (std::mutex, CHandle are two examples used in this PR) - provides easier, less error prone resource management and greatly simplifies logic by allowing to just `return` out of methods instead of doing goto finalization section.
2. Catch all exceptions on the border between shim and inprocess handler to prevent them from leaking up the stack.
Next possible steps:
Use exceptions for flowing HRESULTS - a lot of our methods just receive hresult check if it's failed and return it up the stack - this is exactly what exceptions are created for.
Easier to review with ?w=1 …

Explore usage of std::mutex and CHandle

---

test/IISIntegration.FunctionalTests/Inprocess/LoggingTests.cs
test/IISIntegration.FunctionalTests/Inprocess/StartupExceptionTests.cs
test/IISIntegration.FunctionalTests/Inprocess/StartupTests.cs
test/IISIntegration.FunctionalTests/OutOfProcess/GlobalVersionTests.cs
test/IISIntegration.FunctionalTests/Utilities/FunctionalTestsBase.cs

There has been some flakiness with checking the test sink's output, like here: https://ci3.dot.net/job/aspnet_IISIntegration/job/dev/job/windows-Configuration_Release_prtest/159/console. We may need to add a timeout here, but one mitigation we can add is disposing the iisexpress process, which should force stdout to be written.

Dispose server before checking test sink

---

build/dependencies.props
src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.csproj
src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj

Likewise, looks like these are not used in 2.2

[2.2] Remove unused .Sources packages

---

build/dependencies.props
src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj

It looks like these .Sources packages aren't actually used. We can consolidate them into just the Kestrel repo.

[2.1] Remove unused .Source packages

---

src/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp
src/AspNetCoreModuleV2/AspNetCore/applicationinfo.h
src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp
src/AspNetCoreModuleV2/AspNetCore/applicationmanager.h
src/AspNetCoreModuleV2/AspNetCore/dllmain.cpp
src/AspNetCoreModuleV2/AspNetCore/globalmodule.cpp
src/AspNetCoreModuleV2/AspNetCore/proxymodule.cpp
src/AspNetCoreModuleV2/AspNetCore/proxymodule.h
src/AspNetCoreModuleV2/AspNetCore/stdafx.h
src/AspNetCoreModuleV2/CommonLib/EventLog.h

1. Remove all of them from precompiled headers
2. Move some to instance fields
3. Move others to statics

Use less global variables in shim

---

samples/NativeIISSample/NativeIISSample.csproj
src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp
test/Common.FunctionalTests/CommonStartupTests.cs

I suspect that [this](http://aspnetci/viewLog.html?buildId=518725&buildTypeId=XPlat_Windows_Win8_Universe) failure of AppOfflineAddedAndRemovedStress is caused by insufficient locking during creation of APPLICATION_INFO that causes duplicated key error in
`| [5.377s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Failed HRESULT returned: 0x800700b7 at c:\buildagent\work\33bdfc1cae7b2a38\modules\iisintegration\src\aspnetcoremodulev2\aspnetcore\applicationmanager.cpp:95 `
https://github.com/aspnet/IISIntegration/blob/1d1b2155c49427ee40639469b2632e76588efe90/src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp#L95
I added an exclusive lock for this case and additional test cases that hammer server with requests during startup.

Aquire exclusive lock when creating application info

---

src/AspNetCoreModuleV2/AspNetCore/ServerErrorApplication.h
src/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp
src/AspNetCoreModuleV2/AspNetCore/proxymodule.cpp
src/AspNetCoreModuleV2/CommonLib/AppOfflineApplication.h
src/AspNetCoreModuleV2/CommonLib/PollingAppOfflineApplication.cpp
src/AspNetCoreModuleV2/CommonLib/PollingAppOfflineApplication.h
src/AspNetCoreModuleV2/CommonLib/application.h
src/AspNetCoreModuleV2/CommonLib/iapplication.h
src/AspNetCoreModuleV2/InProcessRequestHandler/InProcessApplicationBase.cpp
src/AspNetCoreModuleV2/InProcessRequestHandler/InProcessApplicationBase.h
src/AspNetCoreModuleV2/InProcessRequestHandler/ShuttingDownApplication.h
src/AspNetCoreModuleV2/InProcessRequestHandler/StartupExceptionApplication.h
src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.cpp
src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.h
src/AspNetCoreModuleV2/OutOfProcessRequestHandler/outprocessapplication.cpp
src/AspNetCoreModuleV2/OutOfProcessRequestHandler/outprocessapplication.h
src/AspNetCoreModuleV2/RequestHandlerLib/AppOfflineTrackingApplication.cpp
src/AspNetCoreModuleV2/RequestHandlerLib/AppOfflineTrackingApplication.h
test/IIS.Tests/TestServerTest.cs

Because of how things were implemented in the past `IAPPLICATION->QueryStatus()` got interleaved with managed application status we use in `INPROCESS_APPLICATION` this is what causes failures like:
```
Failed   Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineAddedAndRemovedStress(hostingModel: InProcess)
Error Message:
Status code was 500
Expected: True
Actual:   False
Stack Trace:
at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.<>c__DisplayClass4_0.<<StressLoad>g__RunRequests|0>d.MoveNext() in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.StressLoad(HttpClient httpClient, String …
```

Split managed application status and IApplication status

---

build/testsite.props
samples/NativeIISSample/NativeIISSample.csproj
src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.csproj
src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj

When I did https://github.com/aspnet/IISIntegration/pull/1129 I've broken a scenario where native asset is being rebuilt while managed (test project/test site is not).
So I've added explicit project references from csprojes to vcxprojes that would force a rebuild. Unfortunately I had to set `DisableFastUpToDateCheck` to make them work with `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>`
Additionally, I switched to always copying request handler bin local without platform subdirectory. It allows us to copy the handler only once and it would work for both build and publish scenario.

Fix incrementality checks for test projects

---

.vsts-pipelines/templates/build-steps.yml

It results in access denied errors and failed build like https://dotnet.visualstudio.com/public/_build/results?buildId=11193&view=logs

Don't push artifacts in forks

---

src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs

`ASPNETCORE_DETAILEDERRORS` is set by default in `DeployerParameters` so win7/8 tests fail now that we can't just catch an exception and not add the environment variable.

Move ASPNETCORE_DETAILEDERRORS env var to web.config

---

src/AspNetCoreModuleV2/CommonLib/PollingAppOfflineApplication.cpp

Looking at [this ](https://ci3.dot.net/job/aspnet_IISIntegration/job/release_2.2/job/windows-Configuration_Debug_prtest/383/consoleFull) failure of `AppOfflineAddedAndRemovedStress` it looks like `is_regular_file` is throwing:
```
15:51:29    | [1.519s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Detected app_offline file, creating polling application
15:51:29    | [1.519s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] d:\j\workspace\windows-confi---dfc477d1\src\aspnetcoremodulev2\aspnetcore\proxymodule.cpp:106 Unhandled exception: status: Access is denied.
15:51:29    | [1.519s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpress …
```

Catch exceptions thrown by is_regular_file

---

build/testsite.props
test/IIS.FunctionalTests/IIS.FunctionalTests.csproj
test/IISExpress.FunctionalTests/IISExpress.FunctionalTests.csproj

VS is not clever enough to flow incremental checks for native files transitively.

Fix incremental checks for test projects

---

src/AspNetCoreModuleV2/AspNetCore/AppOfflineApplication.cpp
src/AspNetCoreModuleV2/AspNetCore/PollingAppOfflineApplication.cpp
src/AspNetCoreModuleV2/AspNetCore/PollingAppOfflineApplication.h

I missed another exists check in `AppOfflineApplication::ShouldBeStarted` and it threw again.
```
[3.439s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Application went offline
| [3.440s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] d:\b\w\33bdfc1cae7b2a38\modules\iisintegration\src\aspnetcoremodulev2\aspnetcore\proxymodule.cpp:106 Unhandled exception: status: Access is denied.
| [3.440s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: : "D:\b\t\buildTmp\5a35515066174b29af069a9a7a63bdb2\app_offline.htm"
| [3.440s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Detected app_offline file, creating polling application …
```

Fix is_regular_file again

---

src/AspNetCoreModuleV2/OutOfProcessRequestHandler/forwardinghandler.cpp

Fixes: https://github.com/aspnet/IISIntegration/issues/1289
Possibly same issues in V1: https://github.com/aspnet/IISIntegration/issues/1269
When server process is shutting down `GetProcess` call would return `E_APPLICATION_EXITING` this PR makes it so we serve 503 instead of 502 in this case.
https://github.com/aspnet/IISIntegration/blob/e26231b61314b35571c99f032ae7353e72bb4056/src/AspNetCoreModuleV2/OutOfProcessRequestHandler/forwardinghandler.cpp#L143
https://github.com/aspnet/IISIntegration/blob/e26231b61314b35571c99f032ae7353e72bb4056/src/AspNetCoreModuleV2/OutOfProcessRequestHandler/processmanager.cpp#L59-L73

Server 503 if server process is shutting down

---

test/WebSites/Directory.Build.props

We don't need any Internal.SDK features in web projects.
Should help with failures like https://github.com/aspnet/IISIntegration/issues/1313

Remove Internal.Sdk reference from test projects

---

test/IISExpress.FunctionalTests/InProcess/StartupTests.cs

Restoring is what caused mass test failures
And it seems it's not strictly required.

Re-enable --no-restore

---

build/repo.props
build/repo.targets
korebuild-lock.txt
nuget/Microsoft.AspNetCore.AspNetCoreModuleV2.nuspec

These packages are currently excluded from code signing, but they should be included, even though they are only used internally and don't go to nuget.org.

Code-sign Microsoft.AspNetCore.AspNetCoreModule and V2 packages
