aspnet/IISIntegration

- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
- src/Microsoft.AspNet.IISPlatformHandler/IPAddressWithPortParser.cs
- test/Microsoft.AspNet.IISPlatformHandler.Tests/HttpPlatformHandlerMiddlewareTests.cs
- test/Microsoft.AspNet.IISPlatformHandler.Tests/IPAddressWithPortParserTests.cs
https://github.com/aspnet/IISIntegration/issues/17
@Tratcher
> Handle Remove header with ip and port correctly

- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
- test/Microsoft.AspNet.IISPlatformHandler.Tests/HttpPlatformHandlerMiddlewareTests.cs
Issue: https://github.com/aspnet/IISIntegration/issues/15
@Tratcher
> Add an option to disable windown auth

- samples/IISSample/Startup.cs
Reacting to https://github.com/aspnet/Logging/pull/314.
> Reacting to verbose rename

- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
#42 
@Tratcher 
Have 6 tests failing locally, but they were failing before this too.
> Remove display name for Negotiate and Ntlm

- samples/IISSample/Startup.cs
- samples/IISSample/hosting.json
- samples/IISSample/project.json
- test/Microsoft.AspNet.IISPlatformHandler.Tests/HttpPlatformHandlerMiddlewareTests.cs
Reacting to https://github.com/aspnet/Hosting/pull/521
> Reacting to new Hosting API

- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddlewareExtensions.cs
Standardizing ConfigureOptions to lambda https://github.com/aspnet/Coherence-Signed/issues/144
> Standardizing middleware to use configureOptions lambda

- IISIntegration.sln
- src/Microsoft.AspNet.Tools.PublishIIS/Microsoft.AspNet.Tools.PublishIIS.xproj
- src/Microsoft.AspNet.Tools.PublishIIS/Program.cs
- src/Microsoft.AspNet.Tools.PublishIIS/WebConfigTransform.cs
- test/Microsoft.AspNet.Tools.PublishIIS.Tests/Microsoft.AspNet.Tools.PublishIIS.Tests.xproj
@moozzyk I think you missed a few things.
> Adding publish iis as a project and minor cleanup

- src/Microsoft.AspNet.IISPlatformHandler/AuthenticationHandler.cs
- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddlewareExtensions.cs
- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerOptions.cs
- src/Microsoft.AspNet.IISPlatformHandler/project.json
- test/Microsoft.AspNet.IISPlatformHandler.Tests/HttpPlatformHandlerMiddlewareTests.cs
https://github.com/aspnet/Options/issues/105
> Updating to new options pattern

- src/Microsoft.AspNet.IISPlatformHandler/IISPlatformHandlerMiddleware.cs
- test/TestSites/StartupNtlmAuthentication.cs
https://github.com/aspnet/Common/issues/85
@blowdart @muratg 
This avoids the issue most of the time. We'll still want to make principal merging smarter at some point.
> Avoid merging with anonymous users.

- src/Microsoft.AspNetCore.IISPlatformHandler/ForwardedTlsConnectionFeature.cs
https://github.com/aspnet/Logging/issues/331
> React to Logging API changes

- .gitattributes
- .gitignore
- build.cmd
- build.sh
- test/Microsoft.AspNetCore.IISPlatformHandler.FunctionalTests/HelloWorldTest.cs
- test/Microsoft.AspNetCore.IISPlatformHandler.FunctionalTests/HttpsTest.cs
- test/Microsoft.AspNetCore.IISPlatformHandler.FunctionalTests/NtlmAuthentationTest.cs
- test/Microsoft.AspNetCore.IISPlatformHandler.Tests/project.json
- test/TestSites/project.json
- test/TestSites/wwwroot/web.config
- test/dotnet-publish-iis.Tests/project.json
> Build with dotnet

- NugetPackageVerifier.json
- src/Microsoft.AspNetCore.IISPlatformHandler/Properties/AssemblyInfo.cs
- src/Microsoft.AspNetCore.IISPlatformHandler/project.json
- src/dotnet-publish-iis/Properties/AssemblyInfo.cs
- src/dotnet-publish-iis/project.json
> Enabled xml doc generation

- src/Microsoft.AspNetCore.Server.IISIntegration/project.json
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/NtlmAuthentationTest.cs
> React to Hosting changes

- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/PublishIISCommand.cs
- src/dotnet-publish-iis/PublishIISCommand.cs
Reacting to https://github.com/aspnet/Announcements/issues/166. May need to scan other repos to see if no longersupporting absolute file paths will break them.
cc @Eilon @DamianEdwards @kichalla @muratg
> Reacting to Configuration API update

- samples/IISSample/Startup.cs
this reference was missed in https://github.com/aspnet/IISIntegration/commit/ee7bb864070ab8c96213f1e4ba803675d9f2ab99
> Rename UseIIS() to UseIISIntegration() in comment

- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs
Removing startupLimitType - it is obsolete in AspNetCoreModule
Addresses #142
> Making the path to app relative for Azure

- IISIntegration.sln
- samples/IISSample/project.json
- samples/IISSample/web.config
- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Microsoft.AspNetCore.Server.IISIntegration.Tools.xproj
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/Helpers.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/NtlmAuthentationTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/project.json
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests.xproj
- test/TestSites.Portable/Program.cs
- test/TestSites.Portable/TestSites.Portable.xproj
- test/TestSites.Portable/project.json
- test/TestSites.Portable/web.config
This needs https://github.com/aspnet/Hosting/pull/719
cc @pakrym @Tratcher
> Convert to portable app

- samples/IISSample/Startup.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
- test/TestSites.Portable/Program.cs
- test/TestSites/Program.cs
Updates for IISIntegration after https://github.com/aspnet/Hosting/pull/730
cc @Tratcher @davidfowl @BrennanConroy 
These can be checked in first.
> React to default hosting configuration changes

- NuGet.config
- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/Program.cs
- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/PublishIISCommand.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests.xproj
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/PublishIISCommandFacts.cs
> Adding support for outputName build option

- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs
> Do not overwrite arguments for portable apps

- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/NtlmAuthentationTest.cs
> Reenable tests and remove kerberos tests #187

- src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tools.Tests/WebConfigTransformFacts.cs
> Always overwrite stdoutLogPath when publishing for Azure

- src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/project.json
Instead of Task.FromResult(0)
@Tratcher
> Use TaskCache class from Microsoft.Extensions.TaskCache.Sources

- src/Microsoft.AspNetCore.Server.IISIntegration/Properties/AssemblyInfo.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISExtensionTests.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/project.json
> Make UseIISIntegration idempotent

- src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs
@kichalla @HaoK
Fixes music store conflict between cookie auth and windows
> Only challenge if not already accepted.

- src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs
Closes: https://github.com/aspnet/IISIntegration/issues/231
@Tratcher
> Avoid calling User.Identity.AuthenticationType

- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/project.json
@pranavkm requires https://github.com/aspnet/Hosting/pull/888
> Add Win7 runtimes to the functional test project

- IISIntegration.sln
- likely would have been a benign issue until we started building the solution file
> CI doesn't have all of the Integration repos side-by-side

- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/Helpers.cs
I can't test this locally (tests pass but nothing really appears to happen). Can anyone point me to instructions?
> React to xUnit change

- build/dependencies.props
- samples/IISSample/IISSample.csproj
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj
- test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.csproj
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/Microsoft.AspNetCore.Server.IISIntegration.Tests.csproj
- test/TestSites/TestSites.csproj
Samples had some code that isn't needed anymore.
> Unify dependency versions to one file and remove workarounds

- src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs
> Set PreferHostingUrls when IIS adding override address

- build/dependencies.props
- samples/IISSample/IISSample.csproj
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj
- test/IISIntegration.FunctionalTests/HelloWorldTest.cs
- test/IISIntegration.FunctionalTests/HttpsTest.cs
- test/IISIntegration.FunctionalTests/IISIntegration.FunctionalTests.csproj
- test/IISIntegration.FunctionalTests/NtlmAuthentationTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/Microsoft.AspNetCore.Server.IISIntegration.Tests.csproj
- test/TestSites/TestSites.csproj
Note the NTLM test is currently disabled due to .NET Core client issues. #82
> Migrate to netcoreapp2.0

- src/Microsoft.AspNetCore.Server.IISIntegration/IISDefaults.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/IISOptions.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs
- test/IISIntegration.FunctionalTests/HelloWorldTest.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs
- test/TestSites/StartupHelloWorld.cs
- test/TestSites/StartupNtlmAuthentication.cs
> Conditionally register auth scheme base on ANCM variable

- src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
- test/Microsoft.AspNetCore.Server.IISIntegration.Tests/IISMiddlewareTests.cs
Addresses #385. For manual testing, I removed the MS-ASPNETCORE-EVENT check and verified the shutdown mechanism.
> Handle ANCM shutdown

- src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/IISOptions.cs
#390 @PinpointTownes
Reverts an un-needed breaking change.
> Add back AutomaticAuthentication for opt-out.

- src/Microsoft.AspNetCore.Server.IISIntegration/baseline.netcore.json
- src/Microsoft.AspNetCore.Server.IISIntegration/breakingchanges.netcore.json
> Add baseline and breaking change files

- src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs
https://github.com/aspnet/Logging/issues/543#issuecomment-321907828
Hosting logs between OnCompleted/RegisterForDispose and DisposeContext. Loggers using IHttpContextAccessor can access User and get ODEs. We can't dispose the user any later, but we can clear it once it's been disposed.
> Clear HttpContext.User when the user is disposed.

- test/IISIntegration.FunctionalTests/HelloWorldTest.cs
- test/IISIntegration.FunctionalTests/HttpsTest.cs
- test/IISIntegration.FunctionalTests/NtlmAuthentationTest.cs
To make CI green
https://github.com/aspnet/IISIntegration/issues/472
> Disable failing tests

- build/repo.props
- build/repo.targets
For hand off to the MSI installer
> Produce a zip with ANCM binaries

- src/AspNetCore/Inc/globalmodule.h
- src/AspNetCore/Src/applicationmanager.cxx
- src/AspNetCore/Src/dllmain.cpp
- src/AspNetCore/Src/globalmodule.cpp
> some fix for handling configuration change and recycling

- Directory.Build.props
- build/dependencies.props
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj
- src/Microsoft.AspNetCore.Server.IISIntegration/Server/IISHttpContext.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/Server/IISHttpContextOfT.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/Server/IISHttpServer.cs
- src/Microsoft.AspNetCore.Server.IISIntegration/Server/OutputProducer.cs
Ignore sources and `t000` versions
> React to pipes in corefx

- build/repo.props
- build/sources.props
- korebuild.json
- version.props
I'm guessing this was messed up during branching? Shouldn't the version be preview2?
> Revert version to preview2

- src/AspNetCore/Src/applicationinfo.cpp
- src/AspNetCore/Src/applicationmanager.cxx
- src/AspNetCore/Src/dllmain.cpp
- src/CommonLib/hostfxr_utility.cpp
- src/CommonLib/utility.cxx
- src/CommonLib/utility.h
- src/RequestHandler/inprocess/inprocessapplication.cpp
- src/RequestHandler/outofprocess/processmanager.cxx
- src/RequestHandler/outofprocess/serverprocess.cxx
> Cleanup LogEvent calls

- build/dependencies.props
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj
https://github.com/aspnet/Home/issues/3040
> React to splitting memory pool

- Directory.Build.props
Addresses: https://github.com/aspnet/IISIntegration/issues/617
> Re-enable API check

- nuget/AspNetCoreV1.nuspec
- nuget/AspNetCoreV2.nuspec
> Adds pdbs (and other files) to testing package

- src/AspNetCoreModuleV2/AspNetCore/src/dllmain.cpp
- src/AspNetCoreModuleV2/AspNetCore/src/proxymodule.cxx
- src/AspNetCoreModuleV2/CommonLib/CommonLib.vcxproj
- src/AspNetCoreModuleV2/CommonLib/debugutil.cpp
- src/AspNetCoreModuleV2/CommonLib/debugutil.h
- src/AspNetCoreModuleV2/CommonLib/exceptions.h
- src/AspNetCoreModuleV2/CommonLib/stdafx.h
- test/CommonLibTests/exception_handler_tests.cpp
new operator might throw, catch all exceptions before they reach IIS.
> Catch all exceptions on ANCM/IIS border

- src/AspNetCoreModuleV2/AspNetCore/src/applicationinfo.cpp
- src/AspNetCoreModuleV2/AspNetCore/src/proxymodule.cxx
- src/AspNetCoreModuleV2/CommonLib/config_utility.h
- src/AspNetCoreModuleV2/CommonLib/debugutil.cpp
- src/AspNetCoreModuleV2/CommonLib/debugutil.h
- src/AspNetCoreModuleV2/CommonLib/exceptions.h
- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.cpp
- src/AspNetCoreModuleV2/CommonLib/hostfxroptions.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.cpp
- test/CommonLibTests/ConfigUtilityTests.cpp
- test/CommonLibTests/inprocess_application_tests.cpp
- test/CommonLibTests/main.cpp
Part of https://github.com/aspnet/IISIntegration/issues/939
> Add diagnostics to hostfxrutil

- src/AspNetCoreModuleV2/CommonLib/CommonLib.vcxproj
- src/AspNetCoreModuleV2/CommonLib/HandleWrapper.h
- src/AspNetCoreModuleV2/CommonLib/exceptions.h
- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.cpp
> Cleanup where.exe invocation

- test/CommonLibTests/CommonLibTests.vcxproj
- test/CommonLibTests/FileOutputManagerTests.cpp
- test/CommonLibTests/GlobalVersionTests.cpp
- test/CommonLibTests/Helpers.cpp
- test/CommonLibTests/Helpers.h
- test/CommonLibTests/main.cpp
May fix https://github.com/aspnet/IISIntegration/issues/959
I suspect we are hitting existing directories that we not cleaned up in previous runs.
> Use guid for temp directories and delete them after tests

- src/AspNetCoreModuleV2/AspNetCore/Inc/aspnetcore_shim_config.h
- src/AspNetCoreModuleV2/AspNetCore/src/aspnetcore_shim_config.cpp
So we can see "schema not found failures" in debug logs.
> Add tracing to shim_config

- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.cpp
- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.h
to 10 seconds
https://github.com/aspnet/IISIntegration/issues/939
> Remove where.exe timeout

- build/repo.targets
- nuget/Microsoft.AspNetCore.AspNetCoreModule.nuspec
- nuget/Microsoft.AspNetCore.AspNetCoreModule.props
- nuget/Microsoft.AspNetCore.AspNetCoreModuleV2.nuspec
- nuget/Microsoft.AspNetCore.AspNetCoreModuleV2.props.in
We need to embed out of process version into a props file and fix some paths
> Fix props files inside Microsoft.AspNetCore.AspNetCoreModule* Nuget packages

- src/AspNetCoreModuleV2/InProcessRequestHandler/managedexports.cxx
- test/IISIntegration.FunctionalTests/Inprocess/ResponseHeaderTests.cs
- test/WebSites/InProcessWebSite/Startup.cs
- test/WebSites/InProcessWebSite/web.config
https://github.com/aspnet/IISIntegration/issues/983
https://github.com/aspnet/IISIntegration/issues/978
> Do not override error responses

- src/AspNetCoreModuleV2/AspNetCore/src/aspnetcore_shim_config.cpp
- src/AspNetCoreModuleV2/CommonLib/config_utility.h
- src/AspNetCoreModuleV2/CommonLib/debugutil.cpp
- src/AspNetCoreModuleV2/CommonLib/utility.cxx
- test/CommonLibTests/ConfigUtilityTests.cpp
https://github.com/aspnet/IISIntegration/issues/988
> Make handlerSettings optional

- src/AspNetCoreModuleV2/AspNetCore/Inc/applicationinfo.h
- src/AspNetCoreModuleV2/AspNetCore/src/applicationinfo.cpp
- src/AspNetCoreModuleV2/CommonLib/application.h
- src/AspNetCoreModuleV2/CommonLib/iapplication.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/dllmain.cxx
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.h
- src/AspNetCoreModuleV2/OutOfProcessRequestHandler/dllmain.cxx
- test/CommonLibTests/inprocess_application_tests.cpp
- test/IISIntegration.FunctionalTests/Inprocess/StartupTests.cs
This fixes https://github.com/aspnet/IISIntegration/issues/993 but is pretty hard to test.
> Pass parameters to createapplication method

- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.cpp
- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.h
- test/IISIntegration.FunctionalTests/Inprocess/StartupTests.cs
https://github.com/aspnet/IISIntegration/issues/1003
> Only run fallback logic for dotnet and dotnet.exe

- src/AspNetCoreModuleV2/AspNetCore/src/applicationinfo.cpp
- src/Microsoft.AspNetCore.Server.IIS/Core/IISHttpContext.FeatureCollection.cs
- src/Microsoft.AspNetCore.Server.IIS/Core/IISHttpContext.cs
- src/Microsoft.AspNetCore.Server.IIS/Core/IO/AsyncIOEngine.cs
- src/Microsoft.AspNetCore.Server.IIS/Core/IO/WebSocketsAsyncIOEngine.cs
- src/Microsoft.AspNetCore.Server.IIS/NativeMethods.cs
- test/IISIntegration.FunctionalTests/Inprocess/ServerVariablesTest.cs
- test/WebSites/InProcessWebSite/Startup.cs
https://github.com/aspnet/IISIntegration/issues/1006
> Sync native calls

- src/AspNetCoreModuleV2/CommonLib/iapplication.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/managedexports.cxx
https://github.com/aspnet/IISIntegration/issues/949
> Fix shutdown race

- build/testsite.props
- src/AspNetCoreModuleV2/AspNetCore/Inc/applicationinfo.h
- src/AspNetCoreModuleV2/AspNetCore/Inc/proxymodule.h
- src/AspNetCoreModuleV2/AspNetCore/src/applicationinfo.cpp
- src/AspNetCoreModuleV2/AspNetCore/src/proxymodule.cxx
- src/AspNetCoreModuleV2/CommonLib/hostfxr_utility.cpp
- src/AspNetCoreModuleV2/CommonLib/irequesthandler.h
- src/AspNetCoreModuleV2/IISLib/ntassert.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/InProcessApplicationBase.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/InProcessRequestHandler.vcxproj
- src/AspNetCoreModuleV2/InProcessRequestHandler/StartupExceptionApplication.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/StartupExceptionHandler.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/dllmain.cxx
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocessapplication.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.cpp
- src/AspNetCoreModuleV2/InProcessRequestHandler/inprocesshandler.h
- src/AspNetCoreModuleV2/InProcessRequestHandler/managedexports.cxx
- src/AspNetCoreModuleV2/InProcessRequestHandler/precomp.cpp
- src/AspNetCoreModuleV2/OutOfProcessRequestHandler/OutOfProcessRequestHandler.vcxproj
- src/AspNetCoreModuleV2/OutOfProcessRequestHandler/dllmain.cxx
- test/CommonLibTests/CommonLibTests.vcxproj
Memory management cleanup here and there.
> Cleanup compilation warnings and re-enable asserts

- test/Common.FunctionalTests/Utilities/IISApplication.cs
If a test failed to create a backup for an apphost.config, copy the one in our repository there globally. This is mostly a work around for CI losing the apphost.config file. For #1027
> Be more resilient to apphost.config issues

- src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.targets
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.csproj
- src/Microsoft.AspNetCore.Server.IISIntegration/Microsoft.AspNetCore.Server.IISIntegration.targets
For #943 and #928. @shirhatti I'll need some help verifying project capabilities because I didn't see it in the binlog.
> Adds project properties and project capabilities to IIS and IISIntegration

- test/IIS.Tests/ClientDisconnectTests.cs
> Disable client disconnect tests

- build/dependencies.props
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj
Verifying now on a win7 VM. For #1069 and to make tests pass on CI 😄
> Add api sets to IntegrationTesting.IIS

- src/Microsoft.AspNetCore.Server.IIS/WebHostBuilderIISExtensions.cs
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISExpressDeployer.cs
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/LoggingHandler.cs
- test/Common.FunctionalTests/Inprocess/HostingEnvironmentTests.cs
- test/Common.FunctionalTests/OutOfProcess/HelloWorldTest.cs
- test/Common.FunctionalTests/Utilities/IISTestSiteFixture.cs
- test/WebSites/InProcessWebSite/InProcessWebSite.csproj
- test/WebSites/InProcessWebSite/Startup.cs
- test/WebSites/OutOfProcessWebSite/OutOfProcessWebSite.csproj
- test/WebSites/OutOfProcessWebSite/Program.cs
- test/WebSites/OutOfProcessWebSite/Startup.cs
Required for https://github.com/aspnet/MetaPackages/pull/278 to pass
> Add content/webroot and current directory tests

- test/Common.FunctionalTests/AppOfflineTests.cs
https://github.com/aspnet/IISIntegration/issues/1130
Looking at https://ci.appveyor.com/project/aspnetci/iisintegration/build/1.0.1775 failure I've noticed that we've managed to make all 5 request in AssertAppOffline between
```
| [0.164s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_outofprocess.dll] Starting app_offline monitoring in application C:\Users\appveyor\AppData\Local\Temp\1\2ad722b7483942139cc715e8e264bd26\
```
and
```
| [0.299s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_outofprocess.dll] Event Log: Application 'C:\Users\appveyor\AppData\Local\Temp\1\2ad722b7483942139cc715e8e264bd26\' was recycled after detecting the app_offline file …
```
> Wait between requests while checking app_offline

- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs
Let's try retrying in this case: https://github.com/aspnet/IISIntegration/issues/1146
> Add ERROR_SHARING_VIOLATION to retry list for IISDeployer.Start

- .vsts-pipelines/templates/build-steps.yml
So we can see why the test process crashes.
> Capture global logs on VSTS

- src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp
We were doing it under shared lock before.
> Initialize logging under exclusive lock

- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeploymentResult.cs
- test/Common.FunctionalTests/AppOfflineTests.cs
- test/Common.FunctionalTests/Inprocess/LoggingTests.cs
- test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs
- test/Common.FunctionalTests/OutOfProcess/HelloWorldTest.cs
- test/Common.FunctionalTests/Utilities/Helpers.cs
- test/IISExpress.FunctionalTests/InProcess/AuthenticationTests.cs
- test/IISExpress.FunctionalTests/InProcess/ShutdownTests.cs
- test/IISExpress.FunctionalTests/InProcess/StartupTests.cs
- test/IISExpress.FunctionalTests/OutOfProcess/GlobalVersionTests.cs
- test/IISExpress.FunctionalTests/OutOfProcess/HttpsTest.cs
- test/IISExpress.FunctionalTests/OutOfProcess/NtlmAuthentationTest.cs
- test/IISExpress.FunctionalTests/UpgradeFeatureDetectionTests.cs
Everything should work without retries.
> Add locked app_oflline file test and remove retrying client

- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs
- test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs
> Fix environmentVariable usage in tests

- src/AspNetCoreModuleV2/AspNetCore/AspNetCore.vcxproj
- src/AspNetCoreModuleV2/AspNetCore/HandlerResolver.cpp
- src/AspNetCoreModuleV2/AspNetCore/HandlerResolver.h
- src/AspNetCoreModuleV2/AspNetCore/applicationinfo.cpp
- src/AspNetCoreModuleV2/AspNetCore/applicationinfo.h
- src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp
- src/AspNetCoreModuleV2/AspNetCore/applicationmanager.h
- src/AspNetCoreModuleV2/AspNetCore/aspnetcore_shim_config.cpp
- src/AspNetCoreModuleV2/AspNetCore/aspnetcore_shim_config.h
- src/AspNetCoreModuleV2/AspNetCore/dllmain.cpp
- src/AspNetCoreModuleV2/AspNetCore/proxymodule.cpp
- src/AspNetCoreModuleV2/CommonLib/HandleWrapper.h
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/XElementExtensions.cs
- test/Common.FunctionalTests/MultiApplicationTests.cs
- test/Common.FunctionalTests/Utilities/EventLogHelpers.cs
- test/Common.FunctionalTests/Utilities/Helpers.cs
- test/WebSites/OutOfProcessWebSite/Startup.cs
Move handler resolution logic and error handling into its own class and add tests for multiple app scenarios.
> Split handler resolution from application info

- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployerBase.cs
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeploymentParameters.cs
- src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISExpressDeployer.cs
https://github.com/aspnet/IISIntegration/issues/1233
> Throw when web config action is added without publish

- test/Common.FunctionalTests/Inprocess/EventLogTests.cs
- test/Common.FunctionalTests/MultiApplicationTests.cs
- test/Common.FunctionalTests/Utilities/EventLogHelpers.cs
- test/IISExpress.FunctionalTests/InProcess/StartupTests.cs
Fixes https://github.com/aspnet/IISIntegration/issues/1100
> Call StopServer before checking all event logs

- build/launchSettings.json
- build/testsite.props
- samples/NativeIISSample/NativeIISSample.csproj
- samples/NativeIISSample/Properties/launchSettings.json
- samples/NativeIISSample/Startup.cs
- src/AspNetCoreModuleV2/AspNetCore/HandlerResolver.cpp
- src/AspNetCoreModuleV2/AspNetCore/applicationmanager.cpp
- src/AspNetCoreModuleV2/AspNetCore/applicationmanager.h
- src/AspNetCoreModuleV2/CommonLib/GlobalVersionUtility.cpp
- test/Common.FunctionalTests/ConfigurationChangeTests.cs
- test/Common.FunctionalTests/Utilities/Helpers.cs
- test/IISExpress.FunctionalTests/OutOfProcess/GlobalVersionTests.cs
- test/WebSites/InProcessWebSite/Properties/launchSettings.json
- test/WebSites/OutOfProcessWebSite/Properties/launchSettings.json
- test/WebSites/OverriddenServerWebSite/Properties/launchSettings.json
- test/WebSites/StartupExceptionWebSite/Properties/launchSettings.json
- test/WebSites/StressTestWebSite/Properties/launchSettings.json
New test doesn't repro https://github.com/aspnet/IISIntegration/issues/1196
Also:
1. Made NativeSample support outofproc if we need to change hosting model for debugging
2. Fixed throwing and catching of exceptions in GlobalVerstionUtility 
3. Cleaned-up eventlog usages
> Add hosting model switch tests
